"""The three service roles a workspace needs, provisioned with boto3.

`launchpad-base` (CDK) creates these for the hub; a console-registered workspace
lives in another region where no stack is deployed, so the bootstrap job has to
create them itself. The statements below are **transcribed from
`infra/stacks/base_stack.py`** and keep the CDK sids, so the two can be diffed
statement by statement during review — the same discipline `agent_iam.py`
follows for per-agent roles.

Deliberate differences from the CDK role (a workspace has no demo layer):

* the gateway role's `hr_lambda.grant_invoke` and `InvokeRestTargets`
  (`execute-api:Invoke` on the office-facts API) statements are absent — those
  targets are CDK-shipped sample *code*, which a boto3 bootstrap does not
  deploy. Nothing else references them.
* names always carry the region. The CDK keeps the original us-west-2 names bare
  (`regional_role_name`), and this module reproduces that rule so a workspace can
  never resolve to a differently-named role than the stack in the same region.

Roles are account-global, so `ensure_role` **refuses an untagged role of the
right name** instead of adopting it: the name may belong to an independent
Launchpad deployment in that region (a CDK stack, or the separate production
install in the same account), and adopting it would silently entangle two
environments.
"""

import json
from collections.abc import Callable
from typing import Any

WORKSPACE_TAG_KEY = "launchpad:workspace"

# Regions whose role names predate multi-region support keep the bare name; see
# infra/stacks/base_stack.py::regional_role_name (kept in sync by hand — the
# backend cannot import the CDK app).
LEGACY_REGION = "us-west-2"

EXECUTION_ROLE_BASE = "launchpad-agent-execution-role"
GATEWAY_ROLE_BASE = "launchpad-gateway-role"
KB_ROLE_BASE = "launchpad-kb-role"
CODEBUILD_ROLE_BASE = "launchpad-codebuild-role"


def regional_role_name(base_name: str, region: str) -> str:
    """Role name for `region`; IAM role names are account-global, not regional."""
    return base_name if region == LEGACY_REGION else f"{base_name}-{region}"


def service_trust_policy(
    service: str, account_id: str, *, source_account: bool = True
) -> dict[str, Any]:
    """Trust policy verbatim from the CDK: the service principal, restricted to
    resources in this account (`aws:SourceAccount`).

    `source_account=False` is for the CodeBuild role, whose CDK counterpart is
    generated by the `codebuild.Project` construct with an unconditioned
    `codebuild.amazonaws.com` trust — a condition the construct does not set is
    one this role must not invent, because a build that cannot assume its role
    fails at package time, not at bootstrap time.
    """
    statement: dict[str, Any] = {
        "Effect": "Allow",
        "Principal": {"Service": service},
        "Action": "sts:AssumeRole",
    }
    if source_account:
        statement["Condition"] = {"StringEquals": {"aws:SourceAccount": account_id}}
    return {"Version": "2012-10-17", "Statement": [statement]}


def execution_role_policy(
    account_id: str, region: str, artifacts_bucket: str, ecr_repo_arn: str
) -> dict[str, Any]:
    """The AgentCore Runtime/Harness execution role — base_stack.py:201-400."""
    bucket_arn = f"arn:aws:s3:::{artifacts_bucket}"
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "BedrockModels",
                "Effect": "Allow",
                "Action": [
                    "bedrock:InvokeModel",
                    "bedrock:InvokeModelWithResponseStream",
                ],
                "Resource": "*",
            },
            {
                # Bedrock Mantle is a separate IAM service from bedrock;
                # bedrock:InvokeModel does not cover it, and a Mantle agent that
                # lacks these deploys fine and then 401s on its first invoke.
                "Sid": "BedrockMantleInference",
                "Effect": "Allow",
                "Action": [
                    "bedrock-mantle:Get*",
                    "bedrock-mantle:List*",
                    "bedrock-mantle:CreateInference",
                ],
                # Mantle models are hosted outside the workspace's region, so the
                # region segment stays wildcarded.
                "Resource": f"arn:aws:bedrock-mantle:*:{account_id}:project/*",
            },
            {
                "Sid": "BedrockMantleCallWithBearerToken",
                "Effect": "Allow",
                "Action": "bedrock-mantle:CallWithBearerToken",
                "Resource": "*",
            },
            {
                "Sid": "MarketplaceOperationsFromBedrockMantleFor3pModels",
                "Effect": "Allow",
                "Action": [
                    "aws-marketplace:Subscribe",
                    "aws-marketplace:ViewSubscriptions",
                ],
                "Resource": "*",
                "Condition": {
                    "StringEquals": {"aws:CalledViaLast": "bedrock-mantle.amazonaws.com"}
                },
            },
            {
                "Sid": "AgentCoreDataPlane",
                "Effect": "Allow",
                "Action": [
                    "bedrock-agentcore:CreateEvent",
                    "bedrock-agentcore:GetEvent",
                    "bedrock-agentcore:ListEvents",
                    "bedrock-agentcore:ListSessions",
                    "bedrock-agentcore:ListActors",
                    "bedrock-agentcore:RetrieveMemoryRecords",
                    "bedrock-agentcore:GetMemoryRecord",
                    "bedrock-agentcore:ListMemoryRecords",
                    "bedrock-agentcore:GetResourceApiKey",
                    "bedrock-agentcore:GetResourceOauth2Token",
                    "bedrock-agentcore:GetWorkloadAccessToken",
                    "bedrock-agentcore:GetWorkloadAccessTokenForJWT",
                    "bedrock-agentcore:GetWorkloadAccessTokenForUserId",
                    "bedrock-agentcore:InvokeCodeInterpreter",
                    "bedrock-agentcore:StartCodeInterpreterSession",
                    "bedrock-agentcore:StopCodeInterpreterSession",
                    "bedrock-agentcore:GetCodeInterpreterSession",
                    "bedrock-agentcore:ConnectBrowserAutomationStream",
                    "bedrock-agentcore:ConnectBrowserLiveViewStream",
                    "bedrock-agentcore:StartBrowserSession",
                    "bedrock-agentcore:StopBrowserSession",
                    "bedrock-agentcore:GetBrowserSession",
                ],
                "Resource": "*",
            },
            {
                "Sid": "EcrPull",
                "Effect": "Allow",
                "Action": ["ecr:GetDownloadUrlForLayer", "ecr:BatchGetImage"],
                "Resource": ecr_repo_arn,
            },
            {
                "Sid": "EcrAuth",
                "Effect": "Allow",
                "Action": "ecr:GetAuthorizationToken",
                "Resource": "*",
            },
            {
                "Sid": "SkillBundleObjects",
                "Effect": "Allow",
                "Action": "s3:GetObject",
                "Resource": f"{bucket_arn}/skills/*",
            },
            {
                "Sid": "SkillBundleList",
                "Effect": "Allow",
                "Action": "s3:ListBucket",
                "Resource": bucket_arn,
                "Condition": {"StringLike": {"s3:prefix": "skills/*"}},
            },
            {
                "Sid": "ABTestOrchestration",
                "Effect": "Allow",
                "Action": [
                    "bedrock-agentcore:GetGateway",
                    "bedrock-agentcore:GetGatewayTarget",
                    "bedrock-agentcore:ListGatewayTargets",
                    "bedrock-agentcore:InvokeAgentRuntime",
                    "bedrock-agentcore:GetConfigurationBundle",
                    "bedrock-agentcore:GetConfigurationBundleVersion",
                    "bedrock-agentcore:ListConfigurationBundleVersions",
                    "bedrock-agentcore:GetOnlineEvaluationConfig",
                    "bedrock-agentcore:GetEvaluator",
                    "bedrock-agentcore:GetABTest",
                    "bedrock-agentcore:StartBatchEvaluation",
                    "bedrock-agentcore:GetBatchEvaluation",
                    "bedrock-agentcore:CreateGatewayRule",
                    "bedrock-agentcore:GetGatewayRule",
                    "bedrock-agentcore:UpdateGatewayRule",
                    "bedrock-agentcore:DeleteGatewayRule",
                    "bedrock-agentcore:ListGatewayRules",
                    "bedrock-agentcore:UpdateGateway",
                ],
                "Resource": "*",
            },
            {
                "Sid": "ManagedKbRetrieval",
                "Effect": "Allow",
                "Action": ["bedrock:Retrieve", "bedrock:GetKnowledgeBase"],
                "Resource": f"arn:aws:bedrock:{region}:{account_id}:knowledge-base/*",
            },
            {
                # AgenticRetrieveStream is not resource-scopable; kept as its own
                # statement so the '*' is visible in isolation.
                "Sid": "ManagedKbAgenticRetrieval",
                "Effect": "Allow",
                "Action": "bedrock:AgenticRetrieveStream",
                "Resource": "*",
            },
            {
                "Sid": "IdentityVaultSecrets",
                "Effect": "Allow",
                "Action": "secretsmanager:GetSecretValue",
                "Resource": (
                    f"arn:aws:secretsmanager:{region}:{account_id}"
                    ":secret:bedrock-agentcore-identity!*"
                ),
            },
            {
                "Sid": "Telemetry",
                "Effect": "Allow",
                "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents",
                    "logs:DescribeLogGroups",
                    "logs:DescribeLogStreams",
                    "logs:StartQuery",
                    "logs:GetQueryResults",
                    "logs:StopQuery",
                    "logs:FilterLogEvents",
                    "logs:GetLogEvents",
                    "xray:PutTraceSegments",
                    "xray:PutTelemetryRecords",
                    "xray:GetSamplingRules",
                    "xray:GetSamplingTargets",
                    "cloudwatch:PutMetricData",
                ],
                "Resource": "*",
            },
        ],
    }


def gateway_role_policy(account_id: str, region: str) -> dict[str, Any]:
    """The AgentCore Gateway service role — base_stack.py:460-555, minus the two
    demo-target statements (see the module docstring)."""
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "IdentityVault",
                "Effect": "Allow",
                "Action": [
                    "bedrock-agentcore:GetResourceApiKey",
                    "bedrock-agentcore:GetResourceOauth2Token",
                    "bedrock-agentcore:GetWorkloadAccessToken",
                ],
                "Resource": "*",
            },
            {
                "Sid": "InvokeRuntimeTargets",
                "Effect": "Allow",
                "Action": [
                    "bedrock-agentcore:InvokeAgentRuntime",
                    "bedrock-agentcore:InvokeAgentRuntimeForUser",
                ],
                "Resource": f"arn:aws:bedrock-agentcore:{region}:{account_id}:runtime/*",
            },
            {
                # A request carrying config-bundle baggage makes the GATEWAY
                # resolve the bundle with this role; without it an agent under a
                # config-bundle A/B loses every Gateway tool.
                "Sid": "ConfigurationBundleRead",
                "Effect": "Allow",
                "Action": [
                    "bedrock-agentcore:GetConfigurationBundle",
                    "bedrock-agentcore:GetConfigurationBundleVersion",
                ],
                "Resource": (
                    f"arn:aws:bedrock-agentcore:{region}:{account_id}"
                    ":configuration-bundle/*"
                ),
            },
            {
                "Sid": "PolicyEngineEvaluation",
                "Effect": "Allow",
                "Action": [
                    "bedrock-agentcore:GetPolicyEngine",
                    "bedrock-agentcore:GetPolicy",
                    "bedrock-agentcore:ListPolicies",
                    "bedrock-agentcore:ListPolicySummaries",
                    "bedrock-agentcore:AuthorizeAction",
                    "bedrock-agentcore:PartiallyAuthorizeActions",
                    "bedrock-agentcore:BatchAuthorizeActions",
                ],
                "Resource": [
                    f"arn:aws:bedrock-agentcore:{region}:{account_id}:policy-engine/*",
                    f"arn:aws:bedrock-agentcore:{region}:{account_id}:gateway/*",
                ],
            },
            {
                "Sid": "IdentitySecrets",
                "Effect": "Allow",
                "Action": "secretsmanager:GetSecretValue",
                "Resource": (
                    f"arn:aws:secretsmanager:{region}:{account_id}"
                    ":secret:bedrock-agentcore-identity!*"
                ),
            },
            {
                "Sid": "ManagedKbRetrieval",
                "Effect": "Allow",
                "Action": ["bedrock:GetKnowledgeBase", "bedrock:Retrieve"],
                "Resource": f"arn:aws:bedrock:{region}:{account_id}:knowledge-base/*",
            },
            {
                "Sid": "ManagedKbAgenticRetrieval",
                "Effect": "Allow",
                "Action": "bedrock:AgenticRetrieveStream",
                "Resource": "*",
            },
        ],
    }


def kb_role_policy(artifacts_bucket: str) -> dict[str, Any]:
    """The Bedrock Managed KB ingestion role — base_stack.py:571-585. Per-KB
    inline policies (`launchpad-kb-{id}`) extend it to external buckets."""
    bucket_arn = f"arn:aws:s3:::{artifacts_bucket}"
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "KbDataObjects",
                "Effect": "Allow",
                "Action": "s3:GetObject",
                "Resource": f"{bucket_arn}/kb/*",
            },
            {
                "Sid": "KbDataList",
                "Effect": "Allow",
                "Action": "s3:ListBucket",
                "Resource": bucket_arn,
                "Condition": {"StringLike": {"s3:prefix": "kb/*"}},
            },
        ],
    }


def codebuild_role_policy(
    account_id: str, region: str, artifacts_bucket: str, ecr_repo_arn: str, project: str
) -> dict[str, Any]:
    """What the CDK grants the build project implicitly (`repo.grant_pull_push`,
    `artifacts.grant_read`) plus its log group, written out."""
    bucket_arn = f"arn:aws:s3:::{artifacts_bucket}"
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "EcrAuth",
                "Effect": "Allow",
                "Action": "ecr:GetAuthorizationToken",
                "Resource": "*",
            },
            {
                # Exactly what `repo.grant_pull_push` grants — the buildspec only
                # logs in, builds and pushes. Reading image metadata
                # (`ecr:DescribeImages`, for the digest) is the backend's job with
                # its own credentials, so the build role does not get it.
                "Sid": "EcrPullPush",
                "Effect": "Allow",
                "Action": [
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:BatchGetImage",
                    "ecr:GetDownloadUrlForLayer",
                    "ecr:InitiateLayerUpload",
                    "ecr:UploadLayerPart",
                    "ecr:CompleteLayerUpload",
                    "ecr:PutImage",
                ],
                "Resource": ecr_repo_arn,
            },
            {
                "Sid": "SourceObjects",
                "Effect": "Allow",
                "Action": ["s3:GetObject", "s3:GetObjectVersion"],
                "Resource": f"{bucket_arn}/*",
            },
            {
                "Sid": "SourceList",
                "Effect": "Allow",
                "Action": ["s3:ListBucket", "s3:GetBucketLocation"],
                "Resource": bucket_arn,
            },
            {
                "Sid": "BuildLogs",
                "Effect": "Allow",
                "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents",
                ],
                "Resource": [
                    f"arn:aws:logs:{region}:{account_id}:log-group:/aws/codebuild/{project}",
                    f"arn:aws:logs:{region}:{account_id}:log-group:/aws/codebuild/{project}:*",
                ],
            },
        ],
    }


class ForeignResourceError(RuntimeError):
    """A resource of the right name exists but was not made for this workspace."""


def _is_already_exists(exc: Exception) -> bool:
    # Same shape as agent_iam._is_already_exists: botocore's exception classes are
    # generated per client, so there is no importable type to catch.
    return "EntityAlreadyExists" in f"{type(exc).__name__}{exc}"


def _tags(iam: Any, role_name: str) -> dict[str, str]:
    return {
        str(tag.get("Key")): str(tag.get("Value"))
        for tag in iam.list_role_tags(RoleName=role_name).get("Tags", [])
    }


def ensure_role(
    iam: Any,
    *,
    workspace_id: str,
    role_name: str,
    trust_policy: dict[str, Any],
    inline_policies: dict[str, dict[str, Any]],
    description: str,
    log: Callable[[str], None] = lambda _m: None,
) -> str:
    """Create or reconcile one workspace service role; return its ARN.

    Idempotent by name, because the bootstrap job resumes and re-enters stages.
    An existing role is adopted **only** when it carries the
    `launchpad:workspace` tag — an untagged one of the same name belongs to a
    deployment this job did not make (the CDK stack, or another install in the
    same account), and adopting it would hand two environments one role. A tag
    naming a different workspace is adopted and re-stamped: only one workspace
    can exist per (account, region), so the previous owner is gone.
    """
    try:
        created = iam.create_role(
            RoleName=role_name,
            AssumeRolePolicyDocument=json.dumps(trust_policy),
            Description=description,
            Tags=[
                {"Key": WORKSPACE_TAG_KEY, "Value": workspace_id},
                {"Key": "launchpad:managed", "Value": "true"},
            ],
        )
        role_arn = created["Role"]["Arn"]
        log(f"created role {role_name}")
    except Exception as exc:  # noqa: BLE001 — the SDK's typed error is client-specific
        if not _is_already_exists(exc):
            raise
        tags = _tags(iam, role_name)
        owner = tags.get(WORKSPACE_TAG_KEY)
        if owner is None:
            raise ForeignResourceError(
                f"IAM role {role_name} already exists without a "
                f"{WORKSPACE_TAG_KEY} tag — it belongs to another Launchpad "
                "deployment (the launchpad-base CDK stack, or a separate install "
                "in this account). Register this workspace in a region that does "
                "not already host one, or remove the role first."
            ) from exc
        role_arn = iam.get_role(RoleName=role_name)["Role"]["Arn"]
        if owner != workspace_id:
            iam.tag_role(
                RoleName=role_name,
                Tags=[{"Key": WORKSPACE_TAG_KEY, "Value": workspace_id}],
            )
            log(f"adopted role {role_name} from retired workspace '{owner}'")
        else:
            log(f"reusing role {role_name}")
        # Adopting: refresh the trust policy so a tightened condition still lands.
        iam.update_assume_role_policy(
            RoleName=role_name, PolicyDocument=json.dumps(trust_policy)
        )

    for policy_name, document in inline_policies.items():
        iam.put_role_policy(
            RoleName=role_name,
            PolicyName=policy_name,
            PolicyDocument=json.dumps(document),
        )
    return role_arn
